apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    environment: pre-prod
    steps:
      - name: Deploy App10-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].digest }}
          target-environment: pre-prod
          name: App10-Frontend

      - name: Deploy App10-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].digest }}
          target-environment: pre-prod
          name: App10-Backend

      - name: Deploy App10-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].digest }}
          target-environment: pre-prod
          name: App10-APIs
  prod:
    needs: pre-prod
    environment: prod
    steps:
      - name: Deploy App10-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App10-Frontend']['App10-Frontend'].digest }}
          target-environment: prod
          name: App10-Frontend

      - name: Deploy App10-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App10-Backend']['App10-Backend'].digest }}
          target-environment: prod
          name: App10-Backend

      - name: Deploy App10-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App10-APIs']['App10-APIs'].digest }}
          target-environment: prod
          name: App10-APIs
